### ISSUE TITLE
Set Read Counter Limit in FileSettings needs to get moved out of 'if(settings.sdmSettings.sdmFileReadPerm != Permissions.ACCESS_NONE)'

### ISSUE THREAD

**Issue by AndroidCrypto** [johnnyb/ntag424-java#10]
Hi Jon,
As I'm playing with the "Read Counter Limit" now I found a real small issue:

The FileSettings looks like (line 160 ff):

			  if(settings.sdmSettings.sdmFileReadPerm != Permissions.ACCESS_NONE) {
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacInputOffset, 0));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacInputOffset, 1));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacInputOffset, 2));
  
				  if(settings.sdmSettings.sdmOptionEncryptFileData) {
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncOffset, 0));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncOffset, 1));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncOffset, 2));
  
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncLength, 0));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncLength, 1));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncLength, 2));
				  }
  
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacOffset, 0));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacOffset, 1));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacOffset, 2));

				  if(settings.sdmSettings.sdmOptionReadCounterLimit) {
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmReadCounterLimit, 0));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmReadCounterLimit, 1));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmReadCounterLimit, 2));
				  }
			  }

But according to the data sheet (page 67)  there 'SDMReadCtrLimit' have this description:
**[Optional, present if SDMOptions[Bit 5] = 1b] SDMReadCtrLimit value (LSB first)**

The settings above do have this description: '[Optional, present if SDMFileRead access right != Fh]...'

Please move the 'sdmOptionReadCounterLimit' part out of the 'if(...Permissions.ACCESS_NONE)' clause like:

			  if(settings.sdmSettings.sdmFileReadPerm != Permissions.ACCESS_NONE) {
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacInputOffset, 0));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacInputOffset, 1));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacInputOffset, 2));
  
				  if(settings.sdmSettings.sdmOptionEncryptFileData) {
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncOffset, 0));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncOffset, 1));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncOffset, 2));
  
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncLength, 0));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncLength, 1));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmEncLength, 2));
				  }
  
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacOffset, 0));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacOffset, 1));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmMacOffset, 2));
				  /*	
				  if(settings.sdmSettings.sdmOptionReadCounterLimit) {
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmReadCounterLimit, 0));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmReadCounterLimit, 1));
					  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmReadCounterLimit, 2));
				  }
				  */
			  }

			  if(settings.sdmSettings.sdmOptionReadCounterLimit) {
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmReadCounterLimit, 0));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmReadCounterLimit, 1));
				  data.add(ByteUtil.getByteLSB(settings.sdmSettings.sdmReadCounterLimit, 2));
			  }

Greetings
Michael

**Comment by johnnyb** [comment]
Good catch!  Change applied.  I haven't tested it, though.

**Comment by AndroidCrypto** [comment]
I made some more tests (see the result in the other issue (**SDM File Encryption Failing in certain cases** #4) but I can confirm it is working now.

Greetings
Michael
