### ISSUE TITLE
Feature Request: Expose the return code in DnaCommunicator

### ISSUE THREAD

**Issue by AndroidCrypto** [johnnyb/ntag424-java#11]
Hi Jon,
It could be good idea to **expose the return code** of a communication in the DnaCommunicator class like this:

```plaintext
public byte[] returnCode; // 2 bytes like '9100h' or '91AEh'
...
public byte[] transceive(byte[] bytesToSend) throws IOException{
		log("BytesSending", bytesToSend);
		byte[] results = transceiver.apply(bytesToSend);
		log("BytesReceived", results);

		// **added** by AndroidCrypto
		returnCode = null;
		if ((results != null) && (results.length > 1)) {
			returnCode = Arrays.copyOfRange(results, results.length - 2, results.length);
		}
		return results;
	}
```
This is extreme helpful when running some commands as e.g. the 'AESEncryptionMode.authenticateEV2' method is just returning true or false, but with the modification in DnaCommunicator the code would look like:

                    ...
                    success = AESEncryptionMode.authenticateEV2(dnaC, ACCESS_KEY0, Ntag424.FACTORY_KEY);
                    if (success) {
                        writeToUiAppend(output, "AES Authentication SUCCESS");
                    } else {
                        // if the returnCode is '919d' = permission denied the tag is in LRP mode authentication
                        if (Arrays.equals(dnaC.returnCode, Constants.PERMISSION_DENIED_ERROR)) {
                            // try to run the LRP authentication
                            success = LRPEncryptionMode.authenticateLRP(dnaC, ACCESS_KEY0, Ntag424.FACTORY_KEY);
                     ...

When working with a "unknown" tag you need to know if the tag operates in AES or LRP mode and there is just one way to find it out (see page 22 of the data sheet) - you have to run AES or LRP authentication and observe the tags reaction. When running AES encryption and the tag is in LRP mode the response of the tag is '919dh' meaning "Permission denied". That is what my code above is doing. I'm for sure there are more application examples.

Thanks again and greetings
Michael

**Comment by johnnyb** [comment]
Added getLastCommandResult() which gives you the most receive CommandResult object, which includes the two status bytes.  Let me know if that works for you.

**Comment by AndroidCrypto** [comment]
Hi Jon,
Thanks for this, working like expected, issue closed.
Greetings
Michael
