### ISSUE TITLE
Documentation: Missing information in README.md "Key diversification"

### ISSUE THREAD

**Issue by AndroidCrypto** [johnnyb/ntag424-java#12]
Hi Jon,
the readme.md misses an information in the "Key diversification" section.

```plaintext
byte[] masterKey = new byte[]{ /* ... */ };
KeyInfo keyInfo = new KeyInfo();
...
```

Please add the line 
```keyInfo.diversifyKeys = true;```

to activate the diversification, thanks.

Greetings
Michael

**Comment by johnnyb** [comment]
Sweet - thanks.
