### ISSUE TITLE
SDM File Encryption Failing in certain cases

### ISSUE THREAD

**Issue by johnnyb** [johnnyb/ntag424-java#4]
- SDM AES Plain data: working
- SDM AES Encrypted data: FAILURE
- SDM LRP Plain data: FAILURE
- SDM LRP Encrypted Data: FAILURE

[Submitted via email by AndroidCrypto]

**Comment by johnnyb** [comment]
Last I checked LRP encrypted worked fine, but I need to recheck each of these personally.

**Comment by johnnyb** [comment]
AES encrypted data (and MAC) fixed in 04db0fc

**Comment by johnnyb** [comment]
I think this is fixed but it needs testing.  I'm not personally using the file encryption features, and honestly think that they way they implemented it is stupid anyway (why is it mirroring from the NDEF file and not the proprietary data file?).

**Comment by AndroidCrypto** [comment]
As I'm working on a SDM tutorial I made a lot of tests regarding the SUN/SDM feature now, this are the (most positive) results:

**Plaintext SDM**: working for UID only, Read Counter Only and UID + Read Counter in **AES and LRP**
**Encrypted PICC data**: working for UID only, Read Counter Only and UID + Read Counter in **AES and LRP**
**Encrypted PICC data and Encrypted File data**: working for UID + Read Counter in **AES and LRP**

Unfortunately there are two options that nether run with AES or LRP for Encrypted PICC data and Encrypted File data: UID only and Read Counter Only.

With "Change File Setting" call end up with a net.bplearning.ntag424.exception.ProtocolException: **Invalid status result: 919E**.

**Comment by johnnyb** [comment]
Thanks for looking into this!  I will try to debug this soon.

**Comment by johnnyb** [comment]
Looking at the docs, I think this is expected behavior, though maybe I should give a warning about it, or have the NDEF template mechanism force a fix:

"Enabling Secure Dynamic Messaging encryption (SDMOptions[Bit 4] set to 1b) is not allowed if
not both SDMReadCtr and UID are mirrored (i.e. SDMOptions[Bit 7] and SDMOptions[Bit 6] must be set to 1b)"
[pg. 69 of NT4H2421Gx].  

This is on the list of reasons to give a 9E result.

**Comment by johnnyb** [comment]
Modified NdefTemplate so that if you add an encrypted file it will also set the bits for uid and readcounter.
